"""match_id fix

Revision ID: 0cf4292fddb3
Revises: 3f5aee26d2ed
Create Date: 2023-12-26 00:13:25.718434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf4292fddb3'
down_revision: Union[str, None] = '3f5aee26d2ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TennisOdds', sa.Column('match_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TennisOdds', 'match_id')
    # ### end Alembic commands ###
