"""initial

Revision ID: 2dd4b5c18814
Revises: 
Create Date: 2023-12-01 23:58:10.195223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd4b5c18814'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('first_team', sa.String(), nullable=False),
    sa.Column('second_team', sa.String(), nullable=False),
    sa.Column('first_odd', sa.Float(), nullable=False),
    sa.Column('second_odd', sa.Float(), nullable=False),
    sa.Column('first_handicap', sa.String(), nullable=False),
    sa.Column('second_handicap', sa.String(), nullable=False),
    sa.Column('sport_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('team_one', sa.String(), nullable=False),
    sa.Column('team_two', sa.String(), nullable=False),
    sa.Column('winner', sa.String(), nullable=False),
    sa.Column('bet', sa.String(), nullable=False),
    sa.Column('ratio', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Predictions')
    op.drop_table('Odds')
    # ### end Alembic commands ###
