"""rename columns

Revision ID: 357bf7cdfd1a
Revises: 2dd4b5c18814
Create Date: 2023-12-02 00:00:27.268355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357bf7cdfd1a'
down_revision: Union[str, None] = '2dd4b5c18814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Predictions', sa.Column('first_team', sa.String(), nullable=False))
    op.add_column('Predictions', sa.Column('second_team', sa.String(), nullable=False))
    op.drop_column('Predictions', 'team_two')
    op.drop_column('Predictions', 'team_one')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Predictions', sa.Column('team_one', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Predictions', sa.Column('team_two', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Predictions', 'second_team')
    op.drop_column('Predictions', 'first_team')
    # ### end Alembic commands ###
