"""total fix

Revision ID: 3f5aee26d2ed
Revises: ce84c11dbf72
Create Date: 2023-12-25 23:56:19.830479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5aee26d2ed'
down_revision: Union[str, None] = 'ce84c11dbf72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TennisOdds', 'total_b',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('TennisOdds', 'total_m',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TennisOdds', 'total_m',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('TennisOdds', 'total_b',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
