"""new column

Revision ID: 7ed92dc98c00
Revises: 357bf7cdfd1a
Create Date: 2023-12-12 21:39:29.697579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed92dc98c00'
down_revision: Union[str, None] = '357bf7cdfd1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Odds', sa.Column('draw_odd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Odds', 'draw_odd')
    # ### end Alembic commands ###
