"""tennis table

Revision ID: ce84c11dbf72
Revises: 703d87820a95
Create Date: 2023-12-25 23:26:07.983607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce84c11dbf72'
down_revision: Union[str, None] = '703d87820a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TennisOdds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('first_player', sa.String(), nullable=False),
    sa.Column('second_player', sa.String(), nullable=False),
    sa.Column('p1', sa.Float(), nullable=False),
    sa.Column('p2', sa.Float(), nullable=False),
    sa.Column('fora_f1', sa.String(), nullable=False),
    sa.Column('fora_f2', sa.String(), nullable=False),
    sa.Column('total_b', sa.String(), nullable=False),
    sa.Column('total_m', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TennisOdds')
    # ### end Alembic commands ###
